spring.application.name=tatamedobem
spring.profiles.default=dev
server.port=8080

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:12}
