server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tatamedobem}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=${JWT_SECRET:tatamedobem-segredo-super-seguro-para-desenvolvimento-2026}

logging.level.org.springframework.security=INFO
logging.level.br.com.tatamedobem=DEBUG
