server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tatamedobem_homolog}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

security.jwt.secret=${JWT_SECRET:tatamedobem-segredo-super-seguro-homolog-2026}

logging.level.org.springframework.security=WARN
logging.level.br.com.tatamedobem=INFO
